# Perfil "local": NO subir a Git (está en .gitignore). Rota la contraseña si la compartiste en algún sitio.
spring.config.activate.on-profile=local

spring.datasource.url=jdbc:postgresql://ep-rapid-silence-ap8ozajp-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ZMe6gEq7pnIN

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
